// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

namespace server.Migrations
{
    [DbContext(typeof(TicketReservContext))]
    [Migration("20200922201449_InitNigration")]
    partial class InitNigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("server.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsFK1")
                        .HasColumnName("f_team1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsFK2")
                        .HasColumnName("f_team2")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("d_timestamp")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("TeamsFK1");

                    b.HasIndex("TeamsFK2");

                    b.ToTable("cd_games","common");
                });

            modelBuilder.Entity("server.Models.Places", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Busy")
                        .HasColumnName("b_busy")
                        .HasColumnType("bool");

                    b.Property<Guid>("GamesFK")
                        .HasColumnName("f_game")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .HasColumnName("c_number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GamesFK");

                    b.ToTable("cd_places","common");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnName("c_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cs_teams","common");
                });

            modelBuilder.Entity("server.Models.Game", b =>
                {
                    b.HasOne("server.Models.Team", null)
                        .WithMany("Games1")
                        .HasForeignKey("TeamsFK1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Team", null)
                        .WithMany("Games2")
                        .HasForeignKey("TeamsFK2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.Places", b =>
                {
                    b.HasOne("server.Models.Game", null)
                        .WithMany("Places")
                        .HasForeignKey("GamesFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
